// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo2pKzZaQWcPc61vb2xUaK7Cyv5rxRQWk',
    appId: '1:4216931595:web:c7537d4e354b86d70bce0e',
    messagingSenderId: '4216931595',
    projectId: 'mangaread-30388',
    authDomain: 'mangaread-30388.firebaseapp.com',
    storageBucket: 'mangaread-30388.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI19etzhqvhRZKR6dYeMy3C1M9FhCLHx4',
    appId: '1:4216931595:android:5504a0090eff133e0bce0e',
    messagingSenderId: '4216931595',
    projectId: 'mangaread-30388',
    storageBucket: 'mangaread-30388.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfVJFxp5Z_hDlIbycAg1DD6KXSOND8tn8',
    appId: '1:4216931595:ios:93e89635b621bdf70bce0e',
    messagingSenderId: '4216931595',
    projectId: 'mangaread-30388',
    storageBucket: 'mangaread-30388.firebasestorage.app',
    iosBundleId: 'com.example.mangaRead',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfVJFxp5Z_hDlIbycAg1DD6KXSOND8tn8',
    appId: '1:4216931595:ios:93e89635b621bdf70bce0e',
    messagingSenderId: '4216931595',
    projectId: 'mangaread-30388',
    storageBucket: 'mangaread-30388.firebasestorage.app',
    iosBundleId: 'com.example.mangaRead',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo2pKzZaQWcPc61vb2xUaK7Cyv5rxRQWk',
    appId: '1:4216931595:web:3aa00db3d3503ef50bce0e',
    messagingSenderId: '4216931595',
    projectId: 'mangaread-30388',
    authDomain: 'mangaread-30388.firebaseapp.com',
    storageBucket: 'mangaread-30388.firebasestorage.app',
  );

}